# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\x07\x43ommand\x12\x1f\n\x06teleop\x18\x01 \x01(\x0b\x32\x0f.Command.Teleop\x1a\x38\n\x06Teleop\x12\x0f\n\x07\x64rive_x\x18\x01 \x01(\x01\x12\x0f\n\x07\x64rive_y\x18\x02 \x01(\x01\x12\x0c\n\x04lift\x18\x04 \x01(\x01\"\xa9\x02\n\x08Response\x12$\n\x06system\x18\x01 \x01(\x0b\x32\x14.Response.BaseSystem\x12\x1a\n\x03mag\x18\x02 \x01(\x0b\x32\r.Response.Mag\x1a%\n\nBaseSystem\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x01 \x01(\x02\x1a\xb3\x01\n\x03Mag\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x05\x61rray\x18\x02 \x03(\x0b\x32\x19.Response.Mag.Measurement\x12\'\n\x04lift\x18\x03 \x01(\x0b\x32\x19.Response.Mag.Measurement\x1a.\n\x0bMeasurement\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=51
  _COMMAND._serialized_end=151
  _COMMAND_TELEOP._serialized_start=95
  _COMMAND_TELEOP._serialized_end=151
  _RESPONSE._serialized_start=154
  _RESPONSE._serialized_end=451
  _RESPONSE_BASESYSTEM._serialized_start=232
  _RESPONSE_BASESYSTEM._serialized_end=269
  _RESPONSE_MAG._serialized_start=272
  _RESPONSE_MAG._serialized_end=451
  _RESPONSE_MAG_MEASUREMENT._serialized_start=405
  _RESPONSE_MAG_MEASUREMENT._serialized_end=451
# @@protoc_insertion_point(module_scope)
