# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"d\n\x07\x43ommand\x12\x1f\n\x06teleop\x18\x01 \x01(\x0b\x32\x0f.Command.Teleop\x1a\x38\n\x06Teleop\x12\x0f\n\x07\x64rive_x\x18\x01 \x01(\x01\x12\x0f\n\x07\x64rive_y\x18\x02 \x01(\x01\x12\x0c\n\x04lift\x18\x04 \x01(\x01\"1\n\x08Response\x1a%\n\nBaseSystem\x12\x17\n\x0f\x62\x61ttery_voltage\x18\x01 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=18
  _COMMAND._serialized_end=118
  _COMMAND_TELEOP._serialized_start=62
  _COMMAND_TELEOP._serialized_end=118
  _RESPONSE._serialized_start=120
  _RESPONSE._serialized_end=169
  _RESPONSE_BASESYSTEM._serialized_start=132
  _RESPONSE_BASESYSTEM._serialized_end=169
# @@protoc_insertion_point(module_scope)
